author:
  email: surfingbytes@users.noreply.github.com
  homepage: https://github.com/surfingbytes/homeassistant-roborock
  name: surfingbytes
description: Roborock
files:
  - custom_components/roborock-hacs/__init__.py
  - custom_components/roborock-hacs/vacuum.py
keywords:
  - vacuum
  - robot
  - roborock
  - homeassistant
  - home-assistant
  - custom-component
  - python
license: MIT License
name: roborock-hacs
type: component